recruitcoders/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from vagas.views import (CandidaturaCreateView, CandidaturaDeleteView,
                         CandidaturaListView, CurriculoCreateView,
                         CurriculoUpdateView, DashboardCandidaturasListView,
                         DashboardCreateView, DashboardDeleteView,
                         DashboardListView, DashboardUpdateView, Index,
                         VagaDetailView, VagaListView)

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("vagas", VagaListView.as_view(), name="vaga-list-page"),
    path("vagas/<int:pk>", VagaDetailView.as_view(), name="vaga-detail-page"),
    path(
        "vagas/<int:vaga_id>/candidatar/",
        CandidaturaCreateView.as_view(),
        name="candidatura-confirm-page",
    ),
    path("candidaturas", CandidaturaListView.as_view(), name="candidaturas"),
    path(
        "candidatura/<int:pk>/deletar",
        CandidaturaDeleteView.as_view(),
        name="candidatura-delete-page",
    ),
    path("curriculo", CurriculoCreateView.as_view(), name="curriculo"),
    path(
        "curriculo/<int:pk>/editar",
        CurriculoUpdateView.as_view(),
        name="curriculo-update",
    ),
    path("dashboard/", DashboardListView.as_view(), name="dashboard"),
    path(
        "dashboard/vaga/<int:pk>",
        DashboardCandidaturasListView.as_view(),
        name="dashboard-vaga-view",
    ),
    path(
        "dashboard/vaga/criar",
        DashboardCreateView.as_view(),
        name="dashboard-vaga-criar",
    ),
    path(
        "dashboard/vaga/<int:pk>/editar",
        DashboardUpdateView.as_view(),
        name="dashboard-vaga-editar",
    ),
    path(
        "dashboard/vaga/<int:pk>/deletar",
        DashboardDeleteView.as_view(),
        name="dashboard-vaga-deletar",
    ),
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("accounts/", include("allauth.urls")),
    path("api/", include("vagas.api.v1.urls")),
    path("api/v2/", include("vagas.api.v2.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vagas/api/v1/urls.py
from django.urls import include, path

from .views import (CandidaturaListCreateView,
                    CandidaturaRetrieveUpdateDestroyView,
                    EmpresaListCreateView, EmpresaRetrieveUpdateDestroyView,
                    VagaListCreateView, VagaRetrieveUpdateDestroyView)

urlpatterns = [
    path("vagas/", VagaListCreateView.as_view(), name="vaga-list-create"),
    path(
        "vagas/<int:pk>/",
        VagaRetrieveUpdateDestroyView.as_view(),
        name="vaga-detail",
    ),
    path(
        "empresas/",
        EmpresaListCreateView.as_view(),
        name="empresa-list-create",
    ),
    path(
        "empresas/<int:pk>/",
        EmpresaRetrieveUpdateDestroyView.as_view(),
        name="empresa-detail",
    ),
    path(
        "candidaturas/",
        CandidaturaListCreateView.as_view(),
        name="empresa-list-create",
    ),
    path(
        "candidaturas/<int:pk>/",
        CandidaturaRetrieveUpdateDestroyView.as_view(),
        name="empresa-detail",
    ),
]

vagas/api/v2/urls.py
from rest_framework.routers import DefaultRouter

from .views import CandidaturaViewSet, EmpresaViewSet, VagaViewSet

router = DefaultRouter()
router.register(r"vagas", VagaViewSet)
router.register(r"empresas", EmpresaViewSet)
router.register(r"candidaturas", CandidaturaViewSet)
urlpatterns = router.urls

vagas/models.py
from typing import Iterable

from django.contrib.auth.models import User
from django.db import models


class Curriculo(models.Model):
    FORMACOES = (
        ("ensino_fi", "Ensino Fundamental Incompleto"),
        ("ensino_fc", "Ensino Fundamental Completo"),
        ("ensino_mi", "Ensino Médio Incompleto"),
        ("ensino_mc", "Ensino Médio Completo"),
        ("ensino_mti", "Ensino Médio Técnico Incompleto"),
        ("ensino_mtc", "Ensino Médio Técnico Completo"),
        ("ensino_si", "Ensino Superior Incompleto"),
        ("ensino_sc", "Ensino Superior Completo"),
    )

    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    nome_completo = models.CharField(max_length=50, blank=True)
    sobre_mim = models.TextField(blank=True)
    formacao = models.CharField(max_length=22, choices=FORMACOES, blank=True)
    habilidades = models.TextField(blank=True)
    atualizado_em = models.DateTimeField(auto_now=False, null=True)

    def __str__(self):
        return self.usuario.username


class Empresa(models.Model):
    TIPOEMPRESA = (
        ("startup", "StartUp"),
        ("pequenamedia", "Pequena/Média Empresa"),
        ("grande", "Grande Empresa"),
    )

    nome = models.CharField(max_length=50)
    imagem = models.ImageField(upload_to="empresas", blank=True)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField()
    tipo = models.CharField(
        max_length=20, choices=TIPOEMPRESA, default=TIPOEMPRESA[0:0]
    )

    def __str__(self):
        return self.nome

    def get_tipo_display(self):
        return dict(self.TIPOEMPRESA).get(self.tipo, self.tipo)


class Local(models.Model):
    cidade = models.CharField(max_length=30)
    estado = models.CharField(max_length=2)

    def __str__(self):
        return f"{self.cidade} - {self.estado}"


class Vaga(models.Model):
    NIVEIS = (
        ("junior", "Júnior"),
        ("pleno", "Pleno"),
        ("senior", "Sênior"),
    )

    CONTRATOS = (("clt", "CLT"), ("pj", "PJ"), ("estagio", "Estágio"))

    STACKS = (
        ("python", "Python"),
        ("javascript", "JavaScript"),
        ("java", "Java"),
        ("csharp", "C#"),
        ("cplus", "C++"),
    )

    titulo = models.CharField(max_length=30)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    salario = models.DecimalField(max_digits=6, decimal_places=2)
    descricao = models.TextField()

    local = models.ForeignKey(Local, on_delete=models.CASCADE, blank=True)
    experiencia = models.CharField(
        max_length=6, choices=NIVEIS, default=NIVEIS[0:0]
    )
    stack = models.CharField(
        max_length=10, choices=STACKS, default=STACKS[0:0]
    )
    contrato = models.CharField(
        max_length=7, choices=CONTRATOS, default=CONTRATOS[0:0]
    )

    valido_ate = models.DateTimeField()
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateField(auto_now=True)

    qntd_etapas = models.IntegerField()
    is_ativo = models.BooleanField(default=True)

    def __str__(self):
        return self.titulo


class Candidatura(models.Model):
    vaga = models.ForeignKey(Vaga, on_delete=models.CASCADE)
    candidato = models.ForeignKey(User, on_delete=models.CASCADE)
    etapa = models.IntegerField()
    is_ativa = models.BooleanField()

    def __str__(self):
        return (
            f"{self.vaga}: {self.candidato} -  Etapa:"
            f" {self.etapa}/{self.vaga.qntd_etapas}"
        )

vagas/forms.py
from django import forms

from .models import Curriculo, Vaga


class CurriculoForm(forms.ModelForm):
    class Meta:
        model = Curriculo
        fields = ["nome_completo", "sobre_mim", "formacao", "habilidades"]


class VagaForm(forms.ModelForm):
    class Meta:
        model = Vaga
        fields = [
            "titulo",
            "salario",
            "descricao",
            "local",
            "experiencia",
            "stack",
            "contrato",
            "valido_ate",
            "qntd_etapas",
        ]

vagas/api/v1/views.py
from django.contrib.auth.models import Group
from rest_framework import generics, permissions
from rest_framework.permissions import IsAdminUser
from rest_framework.response import Response

from vagas.models import Candidatura, Empresa, Vaga
from vagas.serializers import (CandidaturaSerializer, EmpresaSerializer,
                               VagaSerializer)

# ============ API V1 ============


class VagaListCreateView(generics.ListCreateAPIView):
    queryset = Vaga.objects.all().order_by("atualizado_em")
    serializer_class = VagaSerializer
    permission_classes = [IsAdminUser]


class VagaRetrieveUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Vaga.objects.all()
    serializer_class = VagaSerializer
    permission_classes = [IsAdminUser]


class EmpresaListCreateView(generics.ListCreateAPIView):
    queryset = Empresa.objects.all()
    serializer_class = EmpresaSerializer
    permission_classes = [IsAdminUser]


class EmpresaRetrieveUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Empresa.objects.all()
    serializer_class = EmpresaSerializer
    permission_classes = [IsAdminUser]


class CandidaturaListCreateView(generics.ListCreateAPIView):
    queryset = Candidatura.objects.all()
    serializer_class = CandidaturaSerializer
    permission_classes = [IsAdminUser]


class CandidaturaRetrieveUpdateDestroyView(
    generics.RetrieveUpdateDestroyAPIView
):
    queryset = Candidatura.objects.all()
    serializer_class = CandidaturaSerializer
    permission_classes = [IsAdminUser]

vagas/api/v2/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.permissions import IsAdminUser
from rest_framework.response import Response

from vagas.models import Candidatura, Empresa, Vaga
from vagas.serializers import (CandidaturaSerializer, EmpresaSerializer,
                               VagaSerializer)

# ============ API V2 ============


class VagaViewSet(LoginRequiredMixin, viewsets.ModelViewSet):
    queryset = Vaga.objects.all().order_by("atualizado_em")
    serializer_class = VagaSerializer
    permission_classes = [IsAdminUser]


class EmpresaViewSet(LoginRequiredMixin, viewsets.ModelViewSet):
    queryset = Empresa.objects.all()
    serializer_class = EmpresaSerializer
    permission_classes = [IsAdminUser]


class CandidaturaViewSet(LoginRequiredMixin, viewsets.ModelViewSet):
    queryset = Candidatura.objects.all()
    serializer_class = CandidaturaSerializer
    permission_classes = [IsAdminUser]

vagas/templates/dashboard/dashboard.html
{% extends 'base_dashboard.html' %}

{% load static %}


{% block content %}
<h1>{{request.user.empresa}} | Dashboard</h1>
<div class="dashboard-overview">
    <div class="card">
        <h2>Total de Vagas</h2>
        <p>{{ total_vagas }}</p>
    </div>
    <div class="card">
        <h2>Candidaturas Recebidas</h2>
        <p>{{ total_candidaturas }}</p>
    </div>
    <div class="card">
        <h2>Vagas Ativas</h2>
        <p>{{ vagas_ativas }}</p>
    </div>
    <div class="card">
        <h2>Vagas Encerradas</h2>
        <p>{{ vagas_encerradas }}</p>
    </div>
</div>

<div class="dashboard-section">
    <h2>Minhas Vagas</h2>
    <table>
        <thead>
            <tr>
                <th>Título</th>
                <th>Data de Publicação</th>
                <th>Vencimento</th>
                <th>Status</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>

            {% for vaga in vagas %}

            <tr>
                <td><a href="{% url 'dashboard-vaga-view' vaga.id %}">{{vaga.titulo}}</a></td>
                <td>{{vaga.criado_em}}</td>
                <td>{{vaga.valido_ate}}</td>
                <td>

                    {% if vaga.is_ativo %}
                        Ativo
                    {% else %}
                        Encerrado
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'dashboard-vaga-editar' vaga.id %}"><i class="bi bi-pencil"></i> Editar</a>
                    <a href="{% url 'dashboard-vaga-deletar' vaga.id %}"><i class="bi bi-trash"></i> Excluir</a>
                </td>
            </tr>

            {% endfor %}


            <!-- Outras vagas podem ser listadas aqui -->
        </tbody>
    </table>
</div>
{% endblock content %}

vagas/templates/dashboard/vaga-delete.html
{% extends 'base_dashboard.html' %}

{% load static %}


{% block content %}

<style>
    .delete-container {
        width: 100%;
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        background-color: #f7f7f7;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        text-align: center;
    }

    .delete-container h2 {
        margin-bottom: 20px;
    }

    .delete-container p {
        margin-bottom: 30px;
    }

    .btn {
        padding: 10px 15px;
        margin-right: 10px;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    .btn-danger {
        background-color: #dc3545;
    }

    .btn-danger:hover {
        background-color: #c82333;
    }

    .btn-secondary {
        background-color: #6c757d;
    }

    .btn-secondary:hover {
        background-color: #5a6268;
    }
</style>

<div class="delete-container">
    <h2>Confirmar Exclusão</h2>
    <p>Tem certeza que deseja excluir a vaga "{{ vaga.titulo }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Excluir</button>
        <a href="{% url 'dashboard' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>

{% endblock content %}

vagas/templates/dashboard/vaga-form.html
{% extends 'base_dashboard.html' %}

{% load static %}

{% block content %}
<style>
    .form-container {
        width: 100%;
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        background-color: #f7f7f7;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .form-group {
        margin-bottom: 15px;
    }

    .form-group label {
        font-weight: bold;
        display: block;
        margin-bottom: 5px;
    }

    .form-group input,
    .form-group textarea,
    .form-group select {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    .btn {
        padding: 10px 15px;
        background-color: #007bff;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    .btn:hover {
        background-color: #0056b3;
    }
</style>

<div class="form-container">
    <h2>{% if object %}Editar Vaga{% else %}Criar Nova Vaga{% endif %}</h2>
    <form method="post">
        {% csrf_token %}

        <!-- Título da Vaga -->
        <div class="form-group">
            <label for="id_titulo">Título</label>
            {{ form.titulo }}
        </div>

        <!-- Descrição da Vaga -->
        <div class="form-group">
            <label for="id_descricao">Descrição</label>
            {{ form.descricao }}
        </div>

        <!-- Salário -->
        <div class="form-group">
            <label for="id_salario">Salário</label>
            {{ form.salario }}
        </div>

        <!-- Nível de Experiência -->
        <div class="form-group">
            <label for="id_experiencia">Nível de Experiência</label>
            {{ form.experiencia }}
        </div>

        <!-- Tipo de Contrato -->
        <div class="form-group">
            <label for="id_contrato">Tipo de Contrato</label>
            {{ form.contrato }}
        </div>

        <div class="form-group">
            <label for="id_stack">Stack</label>
            {{ form.stack }}
        </div>

        <div class="form-group">
            <label for="id_local">Local</label>
            {{ form.local }}
        </div>

        <div class="form-group">
            <label for="id_qntd_etapas">Quantidade de Etapas</label>
            {{ form.qntd_etapas }}
        </div>

        <div class="form-group">
            <label for="id_valido_ate">Validade</label>
            <input
                type="text"
                name="valido_ate"
                id="id_valido_ate"
                value="{{ form.valido_ate.value|date:'d/m/Y' }}">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">{% if object %}Atualizar{% else %}Criar{% endif %}</button>
        </div>
    </form>
</div>

{% endblock content %}

vagas/templates/dashboard/vaga-view.html
{% extends 'base_dashboard.html' %}

{% block content %}
<section class="dashboard-section">
    <h2>Candidaturas para a Vaga: {{ object.vaga.titulo }}</h2>
    <p>Atualizado em: {{now}}</p>
    <table class="table">
        <thead>
            <tr>
                <th>Candidato</th>
                <th>Etapa</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for candidatura in candidaturas %}
            <tr>
                <td>{{ candidatura.candidato.username }}</td>
                <td>{{ candidatura.etapa }} / {{ candidatura.vaga.qntd_etapas }}</td>
                <td>{{ candidatura.is_ativa|yesno:"Ativa,Encerrada" }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">Nenhuma candidatura encontrada para esta vaga.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
{% endblock %}